CREATE OR REPLACE NETWORK RULE CONVERSATION_DB.CONVERSATION_ANALYSIS.symbl_apis_network_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('api.symbl.ai', 'api-nebula.symbl.ai');

CREATE OR REPLACE SECRET CONVERSATION_DB.CONVERSATION_ANALYSIS.nebula_api_key TYPE = GENERIC_STRING SECRET_STRING = @nebula_api_key;

GRANT READ ON SECRET CONVERSATION_DB.CONVERSATION_ANALYSIS.nebula_api_key TO ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION CONVERSATION_DB.CONVERSATION_ANALYSIS.symbl_apis_access_integration
  ALLOWED_NETWORK_RULES = (CONVERSATION_DB.CONVERSATION_ANALYSIS.SYMBL_APIS_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (CONVERSATION_DB.CONVERSATION_ANALYSIS.NEBULA_API_KEY)
  ENABLED = true;

GRANT USAGE ON INTEGRATION CONVERSATION_DB.CONVERSATION_ANALYSIS.symbl_apis_access_integration TO ROLE ACCOUNTADMIN;

